steps:
  - name: run pre-deployment tests
    image: node:23-alpine
    commands:
      - npm install -g @usebruno/cli --cache /tmp/.npm --prefer-offline
      - apk add curl
      - curl --retry 60 --retry-connrefused --retry-delay 5 --fail --no-progress-meter http://api:8000/ >/dev/null
      - cd .bruno
      - bru run --env docker
    volumes:
      - /tmp/.npm:/tmp/.npm
      - /var/cache/apk:/etc/apk/cache

when:
  - branch: master
    event:
      - push
      - manual

depends_on:
  - build

services:
  api:
    image: git.06222001.xyz/keannu125/auxsolfastapi:${CI_COMMIT_SHA}
    environment:
      BACKEND_AUXSOL_AUTH_USER: 
        from_secret: BACKEND_AUXSOL_AUTH_USER
      BACKEND_AUXSOL_AUTH_PASSWORD:
        from_secret: BACKEND_AUXSOL_AUTH_PASSWORD
      BACKEND_AUXSOL_INVERTER_ID:
        from_secret: BACKEND_AUXSOL_INVERTER_ID
      BACKEND_AUXSOL_INVERTER_SN:
        from_secret: BACKEND_AUXSOL_INVERTER_SN
